apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:                               # IRSA method, try using existing ESO sa
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

