apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: password
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: password
  data:
  - secretKey: password
    remoteRef:
      key: /internal-euw1/test/password
