apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: saml-keystore-key
  namespace: petsbest-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: saml-keystore      # kubernetes secret name
    creationPolicy: Owner
  data:
    - secretKey: saml-keystore-key.pem   # kubernetes secret key
      remoteRef:
        key: /secret/ew1a/myservice/saml-keystore-key.pem
    - secretKey: saml-keystore-cert.pem  # kubernetes secret key
      remoteRef:
        key: /secret/ew1a/myservice/saml-keystore-cert.pem

# The contents of the SSM Parameter Store path under remoteRef.key will be written to the secret
# under the secretKey. This makes sense if you are writing a raw secret straight to the path.
#
# You can alternatively write JSON data to SSM Parameter Store and reference fields within it:
#
#
#
# NEXT STEPS:
#
# 1. Write some data to Parameter Store
#    ```
#    aws ssm put-parameter \
#     --type SecureString \
#     --region eu-west-1 \
#     --profile dev.admin \
#     --name "/path/to/secret" \
#     --value '{
#       "friends": [
#         {"first": "Dale", "last": "Murphy"},
#         {"first": "Roger", "last": "Craig"},
#         {"first": "Jane", "last": "Murphy"}
#       ]
#     }'
# ```
# 
# 2. Write an ExternalSecret that references the value via ClusterSecretStore
#
#    NOTE: This example just takes the secret data as a blob
#    ```
#    apiVersion: external-secrets.io/v1beta1
#    kind: ExternalSecret
#    metadata:
#      name: my-external-secret
#    spec:
#      refreshInterval: 1h
#      secretStoreRef:
#        name: aws-parameter-store
#        kind: ClusterSecretStore
#      target:
#        name: my-k8s-secret # Secret name in k8s
#        creationPolicy: Owner
#     dataFrom:
#     - extract:
#         key: my-cloud-secret
#
#    NOTE: This example picks fields from the JSON data in Parameter Store
#    ```
#    apiVersion: external-secrets.io/v1beta1
#    kind: ExternalSecret
#    metadata:
#      name: my-external-secret
#    spec:
#      refreshInterval: 1h
#      secretStoreRef:
#        name: aws-parameter-store
#        kind: ClusterSecretStore
#      target:
#        name: my-k8s-secret # Secret name in k8s
#        creationPolicy: Owner
#      data:
#      - secretKey: first-friend-firstname
#        remoteRef:
#          key: my-json-secret
#          property: friends.1.first # Dale
#    ```
#
